[tool.commitizen]
name = "cz_conventional_commits"
version_scheme = "semver2"
version = "0.3.57"
version_files = [
  "VERSION",
]
tag_format = "v$version"
update_changelog_on_bump = true
major_version_zero = true
