#!/usr/bin/env python3
"""Generate the desktop OAuth loopback success/error pages.

Emits two self-contained HTML files (inline CSS + base64-embedded Atkinson
Hyperlegible Next, the app's UI sans) into src-tauri/src/, so the Rust loopback
server can `include_str!` them. Theme-aware via prefers-color-scheme; colors are
copied from the app's design tokens (index.css)."""

import base64
import pathlib

# Anchor to the webui root via this script's location (…/webui/src-tauri/scripts/),
# not the process CWD, so it regenerates identically from anywhere.
WEBUI_ROOT = pathlib.Path(__file__).resolve().parents[2]
FONT_DIR = WEBUI_ROOT / "node_modules/@fontsource/atkinson-hyperlegible-next/files"
OUT_DIR = WEBUI_ROOT / "src-tauri/src"


def b64(name: str) -> str:
    return base64.b64encode((FONT_DIR / name).read_bytes()).decode("ascii")


FONT_400 = b64("atkinson-hyperlegible-next-latin-400-normal.woff2")
FONT_700 = b64("atkinson-hyperlegible-next-latin-700-normal.woff2")


FONT_FACE = f"""
@font-face{{font-family:'Atkinson Hyperlegible Next';font-style:normal;font-weight:400;font-display:swap;src:url(data:font/woff2;base64,{FONT_400}) format('woff2')}}
@font-face{{font-family:'Atkinson Hyperlegible Next';font-style:normal;font-weight:700;font-display:swap;src:url(data:font/woff2;base64,{FONT_700}) format('woff2')}}
"""


# App design tokens for the "noir" theme (webui/src/index.css [data-theme="noir"]
# + its dark variant). Noir is intentionally monochrome — the success icon uses
# the slate `primary`, and red (`destructive`) is the single spot of color,
# reserved for the error state. Noir inverts in dark mode (primary is light).
BASE_CSS = """
*{margin:0;padding:0;box-sizing:border-box}
:root{
  --bg:oklch(0.975 0.002 260);--card:oklch(0.99 0.001 260);--fg:oklch(0.22 0.004 260);
  --muted:oklch(0.50 0.004 260);--border:oklch(0.89 0.003 260);
  --primary:oklch(0.24 0.005 260);--primary-fg:oklch(0.98 0.002 260);
  --destructive:oklch(0.52 0.12 25);--destructive-fg:oklch(0.98 0.002 260);
}
@media (prefers-color-scheme:dark){:root{
  --bg:oklch(0.25 0.005 265);--card:oklch(0.30 0.005 265);--fg:oklch(0.93 0.003 260);
  --muted:oklch(0.62 0.004 260);--border:oklch(1 0 0 / 0.09);
  --primary:oklch(0.92 0.003 260);--primary-fg:oklch(0.25 0.005 265);
  --destructive:oklch(0.55 0.13 25);--destructive-fg:oklch(0.96 0.002 260);
}}
html,body{height:100%}
body{
  font-family:'Atkinson Hyperlegible Next',system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  background:var(--bg);color:var(--fg);
  display:flex;align-items:center;justify-content:center;padding:24px;
  -webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;
}
.card{
  background:var(--card);border:1px solid var(--border);border-radius:12px;
  padding:44px 36px;max-width:400px;width:100%;text-align:center;
  box-shadow:0 1px 2px rgba(0,0,0,0.04),0 12px 32px rgba(0,0,0,0.07);
}
.icon{
  width:56px;height:56px;border-radius:50%;background:var(--icon);color:var(--icon-fg);
  display:flex;align-items:center;justify-content:center;margin:0 auto 20px;
}
.icon svg{width:28px;height:28px}
h1{font-size:20px;font-weight:700;letter-spacing:-0.01em;margin-bottom:10px}
p{font-size:14px;line-height:1.55;color:var(--muted);max-width:290px;margin:0 auto}
.brand{margin-top:28px;font-size:12px;font-weight:700;letter-spacing:0.14em;color:var(--muted);text-transform:uppercase}
"""


CHECK_SVG = (
    '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">'
    '<path d="M20 6 9 17l-5-5" stroke="currentColor" stroke-width="2.5" '
    'stroke-linecap="round" stroke-linejoin="round"/></svg>'
)
CROSS_SVG = (
    '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">'
    '<path d="M18 6 6 18M6 6l12 12" stroke="currentColor" stroke-width="2.5" '
    'stroke-linecap="round" stroke-linejoin="round"/></svg>'
)


def page(*, title: str, icon_var: str, icon_fg: str, svg: str, heading: str, subtext: str) -> str:
    """Assemble one full result page: doctype + head (title, embedded font + CSS,
    with per-page icon colors) + a centered card (icon, heading, subtext, wordmark)."""
    css = f":root{{--icon:{icon_var};--icon-fg:{icon_fg}}}" + BASE_CSS
    return f"""<!doctype html>
<!-- GENERATED by src-tauri/scripts/gen-oauth-pages.py — do not edit by hand.
     Re-run the script to regenerate (e.g. to swap the embedded UI font). -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>{FONT_FACE}{css}</style>
</head>
<body>
<main class="card">
<div class="icon">{svg}</div>
<h1>{heading}</h1>
<p>{subtext}</p>
<div class="brand">Dim0</div>
</main>
</body>
</html>
"""


OUT_DIR.joinpath("oauth-success.html").write_text(
    page(
        title="Signed in — Dim0",
        icon_var="var(--primary)",
        icon_fg="var(--primary-fg)",
        svg=CHECK_SVG,
        heading="You’re signed in",
        subtext="You can close this tab and return to Dim0.",
    ),
    encoding="utf-8",
)
OUT_DIR.joinpath("oauth-error.html").write_text(
    page(
        title="Sign-in failed — Dim0",
        icon_var="var(--destructive)",
        icon_fg="var(--destructive-fg)",
        svg=CROSS_SVG,
        heading="Sign-in failed",
        subtext="You can close this tab and try signing in again from Dim0.",
    ),
    encoding="utf-8",
)
print("wrote", OUT_DIR / "oauth-success.html", "and", OUT_DIR / "oauth-error.html")
